name: NGEN14_chamber_flux
channels:
  - conda-forge
  - defaults
dependencies:
  - nb_conda_kernels=2.3.1
  - notebook=6.5.2
  - pip=22.3.1
  - python=3.10.8
  - r=4.1
  - r-base=4.1.3
  - pip:
    - rpy2==3.5.7

